name: SonarCloud

on:
  push:
    branches:
      - master
    paths:
      - "admin/**"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    name: Admin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-admin-${{ hashFiles('admin/**/package-lock.json') }}
          restore-keys: |
            npm-admin-

      - run: npm ci && npm run test:ci
        working-directory: admin/

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: admin/
