name: SonarCloud

on:
  push:
    branches:
      - master
    paths:
      - "admin/**"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    name: Admin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: .node-version

      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-admin-${{ hashFiles('admin/**/package-lock.json') }}
          restore-keys: |
            npm-admin-

      - name: Cache firebase emulators
        uses: actions/cache@v4
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-firebase-emulators-

      - name: Install dependencies
        run: npm i && npm i -g firebase-tools
        working-directory: admin/

      - name: Test and coverage
        run: firebase emulators:exec --project koukokutori "npm run test:ci --prefix admin"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOUKOKUTORI }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: admin/
